### ISSUE TITLE
找不到导入的文章

### ISSUE THREAD

**Issue by CCSSN** [Lyn4ever29/halo-plugin-export-md#2]
版本2.11
后台文章页面只有回收站，没看到有草稿箱呢

**Comment by CCSSN** [comment]
已经关闭了[ToolBench]，是否要删除才行？

**Comment by Lyn4ever29** [comment]
> 版本2.11
> 后台文章页面只有回收站，没看到有草稿箱呢

很抱歉没有写清楚，导入的就在文章列表中。处于未发布的状态

**Comment by Lyn4ever29** [comment]
> 已经关闭了[ToolBench]，是否要删除才行？
> 

和这个插件的问题只是页面显示错误，和导入无关

**Comment by CCSSN** [comment]
> > 已经关闭了[ToolBench]，是否要删除才行？
> 
> 和这个插件的问题只是页面显示错误，和导入无关

删掉ToolBench，重启halo，显示正常了，感谢
